nguage: node_js

node_js:
  - "0.12"

before_script:
  - git config --global user.email "noreply@travis-ci.org"
  - git config --global user.name "travis-ci"
  - npm install

script:
  - ./node_modules/.bin/gulp deploy
